language: python
python:
  - '3.6'
# command to install dependencies
install:
  - pip install -r server/requirements.txt

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# command to run tests
script:
  - tox -e test-coverage

services:
  - postgresql
